### ISSUE TITLE
MySQL does not always see mapped my.cnf

### ISSUE THREAD

**Issue by joshbenner** [blinkreaction/drude#1]
I have .docker and fig.yml in the root of the project. Often after starting with `fig up -d`, MySQL behaves as if it has not seen the mapped 99-my.cnf file. Sometimes this is obvious if the InnoDB log files are different sizes than in my.cnf (container fails), and if no InnoDB log files exist yet, then MySQL will often suffer from too-small packets and the like.

A hint that MySQL has not read the file is this query: `show variables like 'slow_query_log'`

my.cnf enables the slow query log, so if it is off, then the extra config file has not been read by MySQL.

Oddly: if I temporarily change the name of the mapping to z.cnf, then `fig up db`, the file is read. After that, I can change the name back to 99-my.cnf, and the file is STILL read as expected.

**Comment by lmakarov** [comment]
@joshbenner this may be addressed with https://github.com/blinkreaction/drude/commit/03ab5695673ae77acabf17953df67f53ea8d17ab
Please reopen if you notice the issues again.
