### ISSUE TITLE
Add "dsh diagnose" command

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#100]
We need a single command to output important version numbers/etc. necessary for issues diagnostics:
- dsh version
- cat <path/to>/Vagrantfile | grep box_version
- docker version
- docker-compose version
- ... what else?

CC @achekulaev

**Comment by achekulaev** [comment]
vagrant global-status

**Comment by achekulaev** [comment]
uname -a

**Comment by achekulaev** [comment]
pwd

**Comment by achekulaev** [comment]
output of docker-compose.yml

**Comment by achekulaev** [comment]
ls -la of .drude folder in project to check for custom scripts
ls -la of ~/.ssh to check for keys permissions

**Comment by achekulaev** [comment]
vagrant --version

**Comment by achekulaev** [comment]
maybe command to list vbox network adapters

**Comment by achekulaev** [comment]
possibly automate checking for VT-x enabled
Windows: https://www.microsoft.com/en-us/download/details.aspx?id=592
OSX: sysctl -a | grep machdep.cpu.features | grep VMX

**Comment by lmakarov** [comment]
This list is getting pretty long. I would avoid certain things, like pwd, ls and contents of large files

definitely these:
- uname -a
- if not linux
  - vagrant global-status
  - VBoxManage --version
  - VBoxManage list runningvms
  - VBoxManage list hostonlyifs

**Comment by davekopecek** [comment]
I'd love to see virtual_host.

I created a custom command `vhost` but it's a bit hackish:

```
#!/usr/bin/env bash
## Print the URL of the current project -- http://VIRTUAL_HOST
## Usage:   dsh vhost
## Parameters:
##      none

grep VIRTUAL_HOST "$YML_PATH"/docker-compose.yml | head -n 1 | sed 's/    - VIRTUAL_HOST=/http:\/\//g' | sed 's/,/ http:\/\//g'
```

Output:

```
{ drude-testing } master » dsh vhost                                                                                                 /c/projects/drude-testing
http://drupal7.drude http://drupal7-site1.drude http://drupal7-site2.drude
```

**Comment by lmakarov** [comment]
@davekopecek this looks useful. Please submit as a separate request, since this one is already closed.

**Comment by achekulaev** [comment]
@davekopecek it would be the same code appended to system_information function
