### ISSUE TITLE
Solr documentation

### ISSUE THREAD

**Issue by alexander-danilenko** [blinkreaction/drude#106]
Hi @lmakarov 

There is no documentation about Apache Solr and how to integrate it with Drude, but container is exists in compose.yml file: https://github.com/blinkreaction/drude/blob/develop/docker-compose.yml#L94-L104

**Comment by alexander-danilenko** [comment]
See #107

**Comment by lmakarov** [comment]
Landed in develop
https://github.com/blinkreaction/drude/blob/develop/docs/apache-solr.md
