### ISSUE TITLE
Add "dsh phpcs" command

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#116]
It is currently possible to run `phpcs` with drude via `dsh run phpcs ...`, e.g.

```
dsh run "phpcs \
    --standard=Drupal -n \
    --extensions=php,module,inc,install,test,profile,theme \
    --ignore=*.features.*,*.pages*.inc \
        sites/modules/custom"
```

I propose we add a shortcut for this: `dsh phpcs`.

We should settle on the default arguments, make sure it is possible override then and to pass additional ones.

**Comment by achekulaev** [comment]
> make sure it is possible override then and to pass additional ones.

Maybe we should just make it custom command then?

**Comment by lmakarov** [comment]
@achekulaev I gave it a though and a custom command would probably make sense, since this will allow per project configuration of what `dsh phpcs` (or whatever each team decides to call it) is doing.

In that case we just need docs on the phpcs use case with some examples and a sample custom command file for `dsh phpcs`.

**Comment by achekulaev** [comment]
Done in develop
