### ISSUE TITLE
Illegal instruction line 124 dsh docker compose $*

### ISSUE THREAD

**Issue by omahm** [blinkreaction/drude#117]
Got this error on a clean install and it's due to running on an older (2010) iMac on OSX 10.11
Just a heads up if anyone else is using an older mac.

To fix:
- Install Python: [https://www.python.org/downloads/](https://www.python.org/downloads/) (2.7.11)
- run: sudo pip install -U docker-compose
- Restart

https://github.com/docker/compose/issues/271#issuecomment-113326266

**Comment by achekulaev** [comment]
Thank you for a tip to those who will search for solution for this issue.

**Comment by lmakarov** [comment]
This should not be an issues with recent docker-compose releases (1.7.0+).
The next release (1.6.0) of https://github.com/blinkreaction/boot2docker-vagrant will include updated version references and should address this without workarounds.

**Comment by omahm** [comment]
Excellent, Although now I can't use this excuse to upgrade my Mac :)
