### ISSUE TITLE
Provide a new drush command, `drude-init`

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#12]
This is a feature request.

This drush command would do the following.  I'm going to skip over error handling and just give you the general idea of what I'm picturing:
1. Check to see if the current directory is empty
2. If the current directory is empty, download drupal to a subfolder called `docroot`
3. Check to see if [boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant) is installed.  If not, install it.
4. Download the `.docker` file and the `docker-compose.yml` file
5. Append appropriate DB credentials to your settings.php file
6. Run `vagrant up && docker-compose up -d` or the windows/linux equivalent 

This could also accept an argument like `--no-memcached`

**Comment by lmakarov** [comment]
We now have a bunch of automation commands:
- `dsh install` - Install/check prerequisites, boot2docker and drude config
- `dsh init` - Execute project init script .docker/scripts/drude-init.sh.

See https://github.com/blinkreaction/drude/releases/tag/v1.0.0-rc1

**Comment by mkorostoff** [comment]
Nice!  Congrats, looks awesome!!!!!!!!!!!!!
