### ISSUE TITLE
Add `dsh cleanup` command

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#122]
The following two commands will remove all untagged images and stopped containers:

```
docker ps -aqf status=exited | xargs docker rm -vf
docker images -qf dangling=true | xargs docker rmi
```

**Comment by achekulaev** [comment]
Dangerous command when you have more than 1 project...

**Comment by lmakarov** [comment]
Yeah, removing all stopped containers is probably too radical... :)
These are still very useful if once wants to clean up old garbage.
We could add a confirmation with a warning message.

**Comment by achekulaev** [comment]
done in develop
