### ISSUE TITLE
Conflicts with drupal Adminer module

### ISSUE THREAD

**Issue by beeblook** [blinkreaction/drude#127]
Drupal Adminer module uses iFrame. 
Possible nginx's vhost-proxy sends 'X-Frame-Options' header to deny display content of iframe. 

`Refused to display 'http://test.drude/admin/config/development/adminer/callback?username=&db=drupal' in a frame because it set 'X-Frame-Options' to 'deny'.`

**Comment by lmakarov** [comment]
@beeblook drude's vhost-proxy does not set `X-Frame-Options` (on purpose). I'm also not seeing it on my end in the Response headers - http://take.ms/VEf03

Where exactly do you get it?

**Comment by beeblook** [comment]
Sorry, my bad. You're right, this issue isn't connected with drude. 
I rechecked, the problem is between module and latest adminer script.
