### ISSUE TITLE
Re-evaluate `docker-compose exec` as an option to run commands in `cli`

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#128]
At some point back we decided to not use `docker-compose exec` to run commands in `cli` as it was buggy.
Let's re-evaluate it and if it is stable now, then we should refactor our code to use it instead of low level docker commands.

**Comment by achekulaev** [comment]
I was playing with that code recently. It's quite complex and intertwined and working fine. I think we should keep it as is.

**Comment by lmakarov** [comment]
Since docker plans to retire docker-compose altogether soon, we don't have to deal with this right now. Going to close this issue.
