### ISSUE TITLE
Winpty is missed on Windows

### ISSUE THREAD

**Issue by xxalhixx** [blinkreaction/drude#135]
`

>   if is_windows; then
>       # Workaround - run docker exec via winpty (console.exe) to get a tty console in cygwin.
>       if is_binary_found 'console'; then
>           winpty_cmd='console'
>       else
>           echo-red 'Winpty (console.exe) binary missing.'
>           echo 'Run "dsh install prerequisites" to install it.'
>           exit 1
>       fi
>   fi
> `
> In this code script looks for console.exe. Since [winpty 0.3.0](https://github.com/rprichard/winpty/releases/tag/0.3.0) console.exe was renamed to winpty.exe
> Is replacing echo message by`winpty_cmd='winpty'` will fix this issue?

**Comment by achekulaev** [comment]
@xxalhixx thank you for report. I have fixed it in version (1.20.1). It's not in master yet.

If you need it right now you can update to dev version by running 

```
DRUDE_BRANCH=develop dsh update dsh
```

**Comment by achekulaev** [comment]
@lmakarov I guess candidate for hotfix release
