### ISSUE TITLE
Rename system containers

### ISSUE THREAD

**Issue by achekulaev** [blinkreaction/drude#137]
Drude system containers should have names that will unlikely intersect with any other containers.

It should be considered renaming them:

```
vhost-proxy  -->  drude-vhost-proxy
dns  -->  drude-dns
ssh-agent  -->  drude-ssh-agent
```

for clarity and uniqueness.

**Comment by lmakarov** [comment]
With the naming convention used by docker-compose I don't see how project containers names would ever collide with our system service names:

```
<projectname>_cli_1
<projectname>_db_1
<projectname>_web_1
```

Are there any other reasons to rename the system services?

**Comment by achekulaev** [comment]
@lmakarov people may try out other non-Drude systems. They might already have them installed when they install Drude. People might follow some instruction online to run some other container named dns. It can be CI server with other needs and existing containers where Drude is used. Docker Compose Naming convention may change in future. Possibilities are countless. If Drude container names continue to be ambiguous sooner or later someone will come with weird bugs because he/she already had some container named like this.

Having non-ambiguous names is as essential as having non-ambiguous variable name in your code. It is just code style that was proven to be prerogative of senior level code style.

**Comment by lmakarov** [comment]
@achekulaev while I do not like the longer container names, I agree with your argument. Let's go ahead and rename the system services.
