### ISSUE TITLE
Permanent DB data storage not mount in db service?

### ISSUE THREAD

**Issue by softeg** [blinkreaction/drude#14]
Hi,

Do you have any idea why the Permanent DB data storage (/var/lib/mysql) aren't mounted in my local machine ubuntu ?

i try to create path manually and restart services, always same issue.

Thanks

**Comment by softeg** [comment]
Plz, where i can find /var/lib/mysql mounted ?

**Comment by lmakarov** [comment]
@softeg /var/lib/mysql won't is the path inside the container, not the host.
On the host you can use `docker inspect $(docker-compose ps -q db)` or `docker inspect <container_name>` to find out the actual folder on the host used for that volume.

E.g.:

``` json
...
    "Volumes": {
        "/etc/mysql/conf.d/z_my.cnf": "/mnt/sda1/var/lib/docker/vfs/dir/fd6fa48e5ded95132b2e1b705fe77c4ce8616e028ec7b0ebcb23bb80a1d5d564",
        "/var/lib/mysql": "/mnt/sda1/var/lib/docker/vfs/dir/b8927b81da4728649578c2beb4f9ec7d9c959d9d074c22fd339166b7aa238cb9"
    }
...
```

**Comment by softeg** [comment]
Ok thanks for you response, but if i want to share a Permanent volume  like /var/www  ?

exemle :

# Permanent DB data storage

```
 - /data/mysql:/var/lib/mysql
```

this exemple don't work ?

**Comment by lmakarov** [comment]
That mapping will work, however you may have to `docker-compose rm db` first to get rid of the old volume mapping, then `docker-compose up -d` to map the new one.

**Comment by softeg** [comment]
Thanks it work's.
