### ISSUE TITLE
Update prerequisites error on Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [blinkreaction/drude#140]
When I updated prerequisites on Ubuntu 14.04, I received an error:

> client is newer than server (client API version: 1.23, server API version: 1.22)

Docker client was updated, but docker server was not.

One more prerequisites updating didn't help.
I had to remove docker and reinstall prerequisites. This fixed my problem.

**Comment by achekulaev** [comment]
Fixed in dsh 1.20.3
