### ISSUE TITLE
Provide instructions for contributing to the project

### ISSUE THREAD

**Issue by fuzzbomb** [blinkreaction/drude#152]
What are the develop, master and build branches used for?

Which one should a contributor branch from?

`build` is at 9th April 2015, so I guess that's stale?

**Comment by lmakarov** [comment]
@fuzzbomb please contribute to the default branch: `develop`.
`master` is used for releases and `build` is stale (I will remove it).

We do need contribution instructions in place for the project. Let's use this issue to track that.

**Comment by achekulaev** [comment]
We'll provide instructions in a new project

**Comment by fuzzbomb** [comment]
Closing this since drude is retired
