### ISSUE TITLE
Allow updating dsh wherever it is installed

### ISSUE THREAD

**Issue by fuzzbomb** [blinkreaction/drude#154]
`dsh update dsh` uses `sudo`, and always saves the new copy at `/usr/local/bin/dsh`.

If a user has installed it elsewhere in their `$PATH` (say `~/bin/dsh`) and tries to update, they are prompted for a password, and the new version is saved at `/usr/local/bin/dsh`. Now there are two copies, and depending on how the order of dirs in `$PATH`, the old version may still be in use.

Instead of always saving it to `/usr/local/bin/dsh`, can we update the script in the location it was run from, and only use `sudo` if necessary?

**Comment by achekulaev** [comment]
> only use sudo if necessary

Not sure if there's an easy way to determine if sudo is necessary or not.

**Comment by fuzzbomb** [comment]
Closing this since Drude is retired.
