### ISSUE TITLE
npm Issue - New state of 'nil' is invalid.

### ISSUE THREAD

**Issue by davekopecek** [blinkreaction/drude#157]
I'm running DRUDE on a Windows 10 machine with babun as the terminal.

If I `dsh bash` then run `npm install any-package` I get back `New state of 'nil' invalid` and then get kicked out of the vm's bash terminal and back to babun.

Googling around shows that this may be a UTF-8 windows terminal / docker realted issue:

https://github.com/docker/docker/issues/22345
https://github.com/docker/docker/issues/21323

But I have yet to figure it out.  Is there a magic setting somewhere?
Should this issue go to  /blinkreaction/docker-drupal-varnish?

**Comment by eddiewang** [comment]
Any updates this?

**Comment by achekulaev** [comment]
Unfortunately it's hard to say what's happening and it's most likely between Windows and Docker not Drude's issue. 
Thanks for referencing docker issues @davekopecek .

One user says:

> Piping to /dev/null was my solution

I'm not on Windows and can't check.  Have you tried that as a workaround?

As far as I understand it it's like:

```
npm install any-package > /dev/null
```

**Comment by davekopecek** [comment]
`> /dev/null` works for me.

**Comment by aysark** [comment]
Just ran into this issue, only seems to happen on some commands.  Work around was:
`npm install -g n > /dev/null`

Running Windows 10, can repro on powershell and cmd.

**Comment by vladkras** [comment]
I did install with `--verbose` mode, the `yarn-error.log` was created in project folder with helpful indormation:

> EPROTO: protocol error, symlink ...

that lead me directly to npm/npm#9901

So the problem was with volume mounted to windows host and fixed with

`yarn install --no-bin-links`

**Comment by lmakarov** [comment]
@vladkras thanks for sharing. Looks like for npm the following would be a one-stop fix:

```
npm config set bin-links false
```

Not sure whether a similar global option exists for yarn.
