### ISSUE TITLE
env: bash\r: No such file or directory

### ISSUE THREAD

**Issue by rootical** [blinkreaction/drude#170]
Hello,

I've just made setup of env and a project. When running `dsh init` I get:
`env: bash\r: No such file or directory`

Using OSX 10.11.1, oh-my-zsh. Note: I've been using drude before. This is a new machine

Could you please help to understand the problem?

**Comment by rootical** [comment]
Worth to mention other dsh commands are working.

**Comment by rootical** [comment]
Ok, here is how I fixed the issue:
I had to convert all files in the project directory:

``` bash
brew install dos2unix #installs dos2unix
find . -type f -exec dos2unix {} \; # recursively removes windows related stuff
```

**Comment by achekulaev** [comment]
Bash requires your bash scripts to be in Unix line ending format (\n) not windows (\r\n)
The issue is not related to Drude

**Comment by lmakarov** [comment]
@rootical make sure that every single developer using Windows on your team has git configured with this:

```
git config --global core.autocrlf input
```

This will instruct git to always commit text files with Linux line ending (`\n`).

**Comment by rootical** [comment]
Guys, actually I've just cloned your drude-d8-testing in that project dir :)
Anyway, will do next time. Thanks

**Comment by achekulaev** [comment]
> I've just cloned your drude-d8-testing in that project dir :)

If your `core.autocrlf` setting was `true` then git converted line endings when cloning. It's not a repository problem it's a problem of local git setup.

**Comment by mfa01** [comment]
that happened to me after moving the project to other computer, try to recreate manifest again
