### ISSUE TITLE
Mysql commands broken in dsh v1.21.1

### ISSUE THREAD

**Issue by fuzzbomb** [blinkreaction/drude#177]
Follow on from issue #162 and PR #175.

After upgrading to `dsh v1.21.1` today, `dsh sqlc` stopped working. I got this error:

```
andrew@quinx:~/drude-projects/d8core/docroot$ dsh sqlc
bash: $'\E[?25h\E[0G\E[K\E[?25h\E[0G\E[Kmysql': command not found
```

It's the same error reported by @david-hernandez and @waako in #162.

Reverting to `dsh v1.21.0` solved the problem for me.

In #175, the output of `drush sql-connect` was piped though `sed` to remove some unwanted trailing characters. The same commit also removed the use of `DRUDE_IS_TTY=0` when calling drush. Restoring this also fixes the problem for me.

Patch to follow...

**Comment by fuzzbomb** [comment]
PR #178 restores the use of `DRUDE_IS_TTY=0` in `get_mysql_connect()`

I noticed the `sed` expression was exactly the same as the one used in `clean_string()` so I re-used the comment form there.

I also changed the variable name to `$connection_string`, just because that's what the function is about.

**Comment by achekulaev** [comment]
@fuzzbomb thanks for contribution
