### ISSUE TITLE
Can't init, get blinkreaction/drupal-mysql:5.5 tcp erro

### ISSUE THREAD

**Issue by mminklet** [blinkreaction/drude#180]
Pulling db (blinkreaction/drupal-mysql:5.5)...
ERROR: read tcp 10.0.2.15:34944->52.45.33.149:443: read: connection reset by peer

Is this because the repo is down perhaps?

**Comment by lmakarov** [comment]
This looks to be a random issue with hub.docker.com. I'm able to pull this image without issues.
Such issues are often regional and are gone within 24h.
