### ISSUE TITLE
Not able to boot Drupal after first install

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#2]
# Problem:

After completing the steps in README.md, I am not able to access drupal through docker.
# Steps I Took
1. I created the following folder structure, as specified in [usage](https://github.com/blinkreaction/docker-fig-drupal#usage), steps 1 and steps 2:

```
    drwxr-xr-x@  3 matt  wheel   102 Feb 19 13:45 .docker
    drwxr-xr-x   3 root  staff   102 Feb 27 15:10 .vagrant
    -rwxr-xr-x@  1 matt  wheel  1081 Feb 19 13:45 LICENSE
    -rwxr-xr-x@  1 matt  wheel  2519 Feb 19 13:45 README.md
    -rw-r--r--   1 root  staff  2634 Feb 27 15:10 Vagrantfile
    drwxr-xr-x  29 matt  staff   986 Feb 27 15:19 docroot  <------------- drupal docroot
    -rwxr-xr-x@  1 matt  wheel   987 Feb 19 13:45 fig.yml
```
1. I created a `settings.php` file and added the DB credentials per step 3 of README.md
2. Ran `sudo vagrant up`.  Received the following output:

```
    Bringing machine 'boot2docker' up with 'virtualbox' provider...
    ==> boot2docker: VirtualBox VM is already running.
```
1. Ran `fig up -d`.  Received the following output:

```
Creating docking_dbdata_1...
Pulling image mysql:5.5...
511136ea3c5a: Pull complete

...about 20 more "Pull completes"...

667bb345d412: Pull complete
Status: Downloaded newer image for mysql:5.5
Creating docking_db_1...
Creating docking_web_1...
Pulling image blinkreaction/drupal-nginx-php...
147486faf290: Pulling dependent layers
511136ea3c5a: Download complete

...about 50 more "Download completes"...

27d47432a69b: Download complete
7b5b76ab2462: Download complete
Status: Downloaded newer image for blinkreaction/drupal-nginx-php
```
1. Attempted to navigate to http://192.168.59.103:2375/
2. Saw that the page was unavailable
   ![http 3a 2f 2f192 168 59 103 3a2375 2f is not available](https://cloud.githubusercontent.com/assets/1197335/6421693/4367d356-be9f-11e4-8537-2b2b01fd5e90.png)
3. Opened VirtualBox.  Saw that the VM was powered off.  This is very strange indeed, because note I had just very recently received the message "VirtualBox VM is already running" in response to `vagrant up`:
   ![vb](https://cloud.githubusercontent.com/assets/1197335/6421722/8b1b9ce6-be9f-11e4-9b62-5ef0d0b2e655.png)
4. Booted the VM, and confirmed the IP address:
   ![vms](https://cloud.githubusercontent.com/assets/1197335/6421756/dc4863a6-be9f-11e4-8c4e-c5059a54a4a1.gif)
   I saw that 192.168.59.103 was indeed the correct address
5. Attempted to reload http://192.168.59.103:2375/.
6. Saw that the page was unavailable (see #6 above)

**Comment by lmakarov** [comment]
@MKorostoff the `boot2docker-vm` VM is the stock boot2docker (which came with the docker Mac installed), not the one managed by vagrant ([boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant))

Please do `boot2docker stop` to stop the stock one or `boot2docker destroy` to get rid of it entirely.

([boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant)) has 3 IP addresses defined in the Vagrantfile by default. You can use any of those to access your docker web node:
- 192.168.33.10
- 192.168.33.11
- 192.168.33.12

I'm not quite sure why your VirtualBox does not see the custom boot2docker VM, while vagrant does report it running. I have a feeling you may have two versions of VirtualBox installed somehow?

**Comment by mkorostoff** [comment]
Just updating this for posterity, I'm pretty sure the main problem here was running vagrant with sudo.  Because of the, Vagrant created a VM that the VirtualBox UI did not have permission to read.  I think that's right anyhow.

Once I changed the owner of `~/.vagrant.d/` to be a normal user (not root) I was able to run vagrant without sudo, and VirtualBox could see my VM:

![vb2](https://cloud.githubusercontent.com/assets/1197335/6448286/da9284f8-c0e6-11e4-8da9-7da74854c6e5.png)

**Comment by lmakarov** [comment]
Yep, vagrant should NOT be run as root (with sudo). Here's a good answer confirming this and instructions on getting this resolved: http://stackoverflow.com/a/25691501/4550880

In a nutshell:

```
chown -R <USERNAME> /<VAGRANTFILE-DIRECTORY>/.vagrant/machines/
chown -R <USERNAME> ~/.vagrant.d
```

**Comment by mkorostoff** [comment]
Thanks for the info!
