### ISSUE TITLE
Can't connect to mysql server ?

### ISSUE THREAD

**Issue by softeg** [blinkreaction/drude#22]
My service is runing,but icn't connect with drush sqlc to mysql ?

docker-compose ps      
##   Name                Command               State                    Ports                   

cn_cli_1   /bin/sh -c /opt/startup.sh       Up  
cn_db_1    /entrypoint.sh mysqld            Up      0.0.0.0:3306->3306/tcp  
cn_web_1   /bin/sh -c /opt/startup.sh ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 

root@cli:/var/www/docroot# drush sqlc
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)

Any idea ?

**Comment by lmakarov** [comment]
@softeg your DB settings are not correct - `127.0.0.1` is not the correct DB IP address. Did you follow the instructions [here](https://github.com/blinkreaction/drude/blob/master/.docker/docs/drupal-settings.md#db)?
