### ISSUE TITLE
Error 500 or 403: How to check Apache error logs?

### ISSUE THREAD

**Issue by comxd** [blinkreaction/drude#27]
Hi,

I have an "Error 500" error after #dsh up, I have edited the "project_root" into the docker-compose.yml file with: "- &project_root ".:/var/www/docroot"" and call #dsh reset and I now get an 403 Forbidden.

I have tried #docker logs MYPROJECT_web_1 and MYPROJECT_cli_1 but it not return any informations about this errors.

My project structure:
.docker/
.git/
docroot/
tmp/
docker-compose.yml
README.md

**Comment by comxd** [comment]
I have recreated the project structure from scratch/repo and all containers run normally.

But I can't find the logs apache, mysql, memcache.

**Comment by lmakarov** [comment]
@comxd containers output logs into stdout and stderr.
For now you can view the output via docker-compose: `docker-compose logs` (all containers) or `docker-compose logs <service name>` (a particular service, e.g. web, db).

Long term I will be adding `logs` commands to `dsh`.

**Comment by comxd** [comment]
Thanks for the reply. I have tried but the Apache errors seem to be not populated.

**Comment by kyleskrinak** [comment]
FWIW, I had this problem, and the container output isn't the same as error.log or access.log — which you can get to.

First, get your container's name using docker ps -a. I'm focusing on apache2 problems at the moment, so this is:
`1511250b0c95        blinkreaction/drupal-apache-php:2.2-5.5   "/bin/sh -c '/opt/st   2 minutes ago       Up 2 minutes                192.168.10.12:80->80/tcp, 192.168.10.12:443->443/tcp   statdrude_web_1`

Here, it's " statdrude_web_1"

`docker exec -i -t statdrude_web_1 bash` 
takes me to the apache container. 

I then `/var/log/apache2` and I see access.log and error.log — and I see what's throwing my 500 error.

**Comment by TLyngeJ** [comment]
It should be trivial to add mappings between the container and the host, that allows the container to write the log files from Apache, MySQL, memcache and what not, to the project folder. Something like:

```
web:
    volumes:
        - "./logs/web:/var/log/apache2"
```

**Comment by achekulaev** [comment]
```
dsh bash web
cat /var/log/apache2/access.log
```

@TLyngeJ nice solution

**Comment by comxd** [comment]
Thanks!

**Comment by lmakarov** [comment]
I've been refactoring most of the images to output logs to /dev/stdout. Docker collects those and you can view them with `docker logs <container_name>` or `docker-compose <service_name>`

We've added a wrapper in dsh for this: `dsh logs` or `dsh logs <service_name>`

**Comment by kyleskrinak** [comment]
I do not see the output of /var/log/apache2/error.log using @lmakarov's suggestion, above, when running `dsh logs`.

**Comment by lmakarov** [comment]
@kyleskrinak make sure you are using the latest image versions:

```
docker-compose pull
dsh up
```

Aslo check if your `docker-compose.yml` file is not outdated
https://github.com/blinkreaction/drude/blob/develop/docker-compose.yml

Web (Apache logs) are sent to the web container stdout. View them with `dsh logs web`
CLI (PHP logs) are send to the cli container stdout. View them with `dsh logs cli`

**Comment by kyleskrinak** [comment]
I did have to run updates on drude/dsh. I'll report back after my next troubleshooting session. Thank you!
