### ISSUE TITLE
Connection dies when left idle

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#3]
Steps I took:
- Created a new linux VM with [boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant)
- Created a new container with `fig up -d` and the fig.yml file in this repository
- SSHed to the new container, and installed drupal
- Navigated to http://192.168.10.11/
- Saw that Drupal was installed
- Went to lunch (gone about 30 minutes)
- Returned to see that my SSH session to my new container had terminated with the following error:

```
root@41d21429d40c:/var/www# Couldn't connect to Docker daemon - you might need to run `boot2docker up`.
```
- Saw that my VirtualBox VM was in an "aborted" state (whatever that means)
  ![virtual-box](https://www.monosnap.com/image/3CS6LRITqRr7DUihv0l0WLwiIFEMCd.png)
- Attempted to run `fig run --rm web bash` and received the same error as above
- Attempted to run `fig up -d` and received the same error as above.
- Booted my linux VM in the VirtualBox UI
- Attempted to run `fig up -d` and received the following error:

```
Recreating demo_dbdata_1...
Recreating demo_db_1...
Cannot start container bfa220b0c6e7441ca28acecb8e870011e2846a7171b13cd690f5f0b5273ee83c: Error starting userland proxy: listen tcp 192.168.10.11:3306: bind: cannot assign requested address
```
- Ran the following three commands:

```
vagrant halt
vagrant up
fig up -d
```
- Saw that my container started successfully, with the following message

```
Recreating drupal7_dbdata_1...
Recreating drupal7_db_1...
Recreating drupal7_web_1...
```

**Comment by lmakarov** [comment]
@MKorostoff  this will be pretty difficult to reproduce and debug. Have you experience this issue recently?

**Comment by mkorostoff** [comment]
I'm not sure why this would be closed.  I have not used drude really at all since this was first reported, but I experienced it twice in my week with drude.

**Comment by lmakarov** [comment]
@MKorostoff this was closed for the lack of feedback and since no one else reported a similar issue.
If you continue to use drude and have this issues, then let me know, so it can be debugged.
