### ISSUE TITLE
Sending mail

### ISSUE THREAD

**Issue by comxd** [blinkreaction/drude#30]
Hi,
What do you think of adding sendmail?

php.ini:

```
[mail function]
sendmail_path = /usr/sbin/sendmail -t -i

[sendmail]
smtp_server=example.com
smtp_port=25
```

**Comment by TLyngeJ** [comment]
How about adding [mailcatcher](http://mailcatcher.me/), with an option of bypassing it, so that mails can get sent to a real world SMTP?

**Comment by TLyngeJ** [comment]
I've tried adding mailcatcher to the base apache image, and it works quite well.

Only issue was that I had a hard time figuring out how to set apache up, so that it would act like a reverse proxy to the mailcatcher web interface.

**Comment by lmakarov** [comment]
Added instructions for sending/capturing email via MailHog in 3e8be1eb009a489050fe6c1a76696a8a06f88860

**Comment by sch4lly** [comment]
Hi! I tried sending mails using your instructions, but did not get it to work. It seems you have to install and configure sSMTP on the `web` box, instead of `cli`, at least this works for me.

**Comment by TLyngeJ** [comment]
Strange. I've done this like a gazillion times (I have the mail install done during `dsh init`) and it always worked on the CLI container.

**Comment by lmakarov** [comment]
@sch4lly what images are you using for web and cli?
PHP used to run in the web container alongside apache a long time ago. Now there is only apache in web. Apache does not send email, so there is no point or need in having sSMTP in the web container.

**Comment by sch4lly** [comment]
@lmakarov I'm using the nginx images, maybe thats the problem

**Comment by lmakarov** [comment]
Oh... that makes sense now. I even forgot we have an nginx web image.
Just in case - would you be interested to refactor it to follow the web (nginx) + cli (php-fpm) approach?

**Comment by sch4lly** [comment]
Sure, I will try! Might take some time though.

**Comment by achekulaev** [comment]
@lmakarov I guess we need to remove nginx image at the moment so people wouldn't get confused.
