### ISSUE TITLE
Add drush rebuild-registry ("rr") command to CLI container.

### ISSUE THREAD

**Issue by chipkaye** [blinkreaction/drude#32]
https://www.drupal.org/project/registry_rebuild

**Comment by lmakarov** [comment]
Resolved in https://github.com/blinkreaction/docker-drupal-cli/commit/344eb6b37bc17c74995fde761443057e2dd2f891#diff-3254677a7917c6c01f55212f86c57fbf

`docker-compose pull` to get the latest cli image, then `dsh up` to restart containers.
