### ISSUE TITLE
Cannot use mysql from command line

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#4]
## Steps to reproduce:
1. Boot up a container with fig
2. Run `fig run --rm web bash`
3. Run `mysql`
4. Receive the error: `Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
   ![term](https://cloud.githubusercontent.com/assets/1197335/6448475/3d0f1bae-c0e8-11e4-976c-96eb7b82e0fc.png)
## Expected behavior

That I would enter an interactive mysql command prompt

**Comment by lmakarov** [comment]
MySQL is in a different container and not available locally.
Use `drush sqlc` to connect to the site's DB.
You can also connect to the DB container with an external client on your host with the container IP:port for mysql defined in the fig.yml file.

**Comment by mkorostoff** [comment]
Thanks!
