### ISSUE TITLE
Conflicts with existing docker/boot2docker installation

### ISSUE THREAD

**Issue by frankcarey** [blinkreaction/drude#40]
Since I already have boot2docker installed on OSX, and DOCKER_\* paths in my ~/.zshrc file, this causes conflicts when I install drude.

Namely I get this error: 

```
$ dsh up
Bringing machine 'boot2docker' up with 'virtualbox' provider...
==> boot2docker: Checking if box 'blinkreaction/boot2docker' is up to date...
==> boot2docker: VirtualBox VM is already running.
Starting containers...
SSL error: [Errno 1] _ssl.c:504: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number
```

Using docker ps directly I get

```
$ docker ps
FATA[0000] An error occurred trying to connect: Get https://localhost:2375/v1.18/containers/json: tls: oversized record received with length 20527
```

Issue was that I had these env flags already set:

```
$ printenv
...
DOCKER_CERT_PATH=/Users/fcarey/.boot2docker/certs/boot2docker-vm
DOCKER_TLS_VERIFY=1
```

I commented these out in my ~/.zshrc file and then it works
### Potential solutions
- Look for the existence of these ENV vars either before up runs or when it installs and throw a warning.

**Comment by lmakarov** [comment]
Addressed in 69155161016673c9f6fe44987dbc2d9f4d7ec07a
