### ISSUE TITLE
How to use behat

### ISSUE THREAD

**Issue by kadu** [blinkreaction/drude#51]
Hi, I'm trying to use behat on my project, when I run dsh behat I have a series of error on screen:

Could not open connection: Curl error thrown for http POST to http://browser:4444/wd/hub/session with params: {"desiredCapabilities":{"tags":["cli","PHP 5.6.10-1+deb.sury.org~precise+1"],"browser":"firefox","version":"","browserName":"firefox","browserVersion":"","platform":"ANY","ignoreZoomSetting":"false","name":"Behat feature suite","deviceOrientation":"portrait","deviceType":"tablet"}}
    ╳  
    ╳  Couldn't resolve host 'browser' (Behat\Mink\Exception\DriverException)

what I need to configure to  run "dsh behat" correctly

**Comment by achekulaev** [comment]
@kadu please see https://github.com/blinkreaction/drude/blob/master/docs/behat.md

**Comment by kadu** [comment]
@achekulaev Tks, my machine was a chorme, and my behat conf was firefox, after some investigation found the problem. thanks. (I just download a firefox container)
