### ISSUE TITLE
Amend `dsh status` command

### ISSUE THREAD

**Issue by TLyngeJ** [blinkreaction/drude#55]
As a technician I find the `dsh status` command useful, but as a developer, I'd much more prefer a list with links to the available websites, in favor of the command executed on the container.

Something like:

```
     Name                   URL               State                       Ports                     
-------------------------------------------------------------------------------------------------------
site_cli_1                                    Up      9000/tcp                                      
site_db_1                                     Up      0.0.0.0:32816->3306/tcp                       
site_solr_1   http://localhost:32817/solr     Up      0.0.0.0:32817->8983/tcp                       
site_web_1    http://localhost:32819          Up      0.0.0.0:32818->443/tcp, 0.0.0.0:32819->80/tcp
```

Maybe the original output could be achieved by adding a -v, for verbose, or something.

**Comment by achekulaev** [comment]
I'm sorry I can't think of any way dsh could possibly know about links to websites you have.

**Comment by achekulaev** [comment]
@TLyngeJ I'm open to propositions how to do it. At the moment `dsh st` shows you output of `docker-compose ps`.

**Comment by TLyngeJ** [comment]
Ohh, I thought that dsh was building that table. That complicates things a bit.

**Comment by TLyngeJ** [comment]
After the DNS discovery and proxy has been implemented this won't bee needed.
