### ISSUE TITLE
`dsh` changes the file permissions

### ISSUE THREAD

**Issue by TLyngeJ** [blinkreaction/drude#56]
When doing `dsh drush up drupal` the CLI container changes the file permissions to root (I recon that's cause the CLI commands are running as root), which is slightly breaking the site, and make git unable to control the files.

I could come up with a ton of ideas on how to solve this (setting the user name in YAML file, scripts that picks up the usename from the host, etc) but none of them are, in my opinion, very good.

What would be a good way to solve this issue?

**Comment by achekulaev** [comment]
What's your OS?

**Comment by TLyngeJ** [comment]
Linux, distribution is Ubuntu.

**Comment by achekulaev** [comment]
So at the moment there is no solution from Docker for that. "Massive recursive chowns" is the only straightforward solution. 

Potentially at container start we could take current user id on host, create user with the same id inside the container and employ that user (not root) to run everything. But that's a pretty massive change with many potential problems that is not going to happen soon. But we'll keep it in mind

**Comment by TLyngeJ** [comment]
If you believe that a "Massive recursive chowns" is the only straightforward solution, then why can't that take place in the docker-drupal-cli's statup.sh script? As the very last thing before exit.

I know this isn't a current issue if you run docker in a VM but it is on Linux. And it will become a very big issue when OSX and Windows can run docker natively.

**Comment by achekulaev** [comment]
I'm not sure if we are talking about the same thing. By "massive chown" I mean 

```
sudo chown -R `whoami` /path/to/project
```

You're not updating Drupal every day don't you? Running one command to apply proper permissions doesn't look like lots of pain. Or am I missing some common scenario you have to deal with every day?
Chown-ing in `startup.sh` is a mere band-aid. You'd have to restart container each time. What's the point of restarting container to set proper permissions vs just running one command to set proper permissions? You can even create bash alias if you're doing it often.

I understand that you're frustrated with the issue but we have pretty limited resources for this project and 90% of our users are on mac or windows. So it's pretty low in priorities list at the moment while it's scope is pretty large as compared to issue it creates:
1) implement transfer of current host's uid and gid to docker via ENV vars (update instructions and default docker-compose files)
2) use that username to run all container's processes and make sure that it doesn't break anything in our process.

p.s. it's quite unlikely that win or mac will ever be able to run docker natively as docker uses specific Linux core virtualization features.

**Comment by lmakarov** [comment]
@TLyngeJ @achekulaev and I discussed the the scope of "making this work properly" on Linux.

This is doable with a bunch of workarounds:
- passing the Linux user UID to the container
- setting up a user with this UID at container startup
- making sure this user has appropriate access
- making sure this works across all docker images we are currently using (which may be affected by this issue)

As you can imaging the scope is pretty large and the effort will take a considerable amount of time.
Unfortunately I do not know about a better (and easier) solution right now.

One other option I can think of is using [boot2docker-vagrant](https://github.com/blinkreaction/boot2docker-vagrant) on Linux. This is a blunt approach, however it is  the only one that would normalize the experience across all environments.

**Comment by TLyngeJ** [comment]
@achekulaev You are absolutely right. I don't do it every day. But I do it a couple of times every month on around 20 sites. So for people that really uses docker heavily, this is a party stopper.

My personal solution for this issue is this:

```
#!/bin/bash
useradd $wwwuser -m -s /bin/bash
sed -i "s/www-data/$wwwuser/g" /etc/apache2/envvars
source /etc/apache2/envvars
exec apache2 -D FOREGROUND
```

`$wwwuser` is an environment variable set in the docker-compose.yml.

And doing something similar shouldn't be that difficult in your setup, as you "just" need to SSH into the apache container using that user.

Regarding the "it's quite unlikely that win or mac will ever be able to run docker natively". Microsoft is an active contributor to the Docker project and has stated that it will support Docker. Try Google, and you'll see posts like http://www.infoworld.com/article/2907642/application-virtualization/microsoft-docker-for-windows-server-is-right-around-the-corner.html. But they will, of course, focus on getting Windows specific features to work in Docker, so getting Ubuntu running through Docker is probably not gonna happen anytime soon.

Apple has a strange history of not listening to their audience, but I don't think they can escape this. So this will probably be sneaked into OS X at some point. And they should be able to wrap some system calls so that they will be usable from an Ubuntu running in a Docker container.

@lmakarov boot2docker is the workaround that allows non-linux users to enjoy Docker. And one of the side effects is this file permission thing. So start using middle-ware to "normalize" (which in this case would mean "doing stuff equally wrong") is a path that seems so wrong, that I would never even consider it. Installing Windows, and use boot2docker would be a more suitable approach IMO.

As I wrote, this is a show-stopper for me, as a lot of my co-workers cannot use this as it is, but I'll be keeping an eye on this project, as it's definitely on to something right.

**Comment by achekulaev** [comment]
> My personal solution for this issue is this

Thanks for sharing. It's a surprise that this works for you. Am I getting right that `$wwwuser` contains **username** of your current user? It's just weird that it works because I guess `uid` of that user inside container doesn't match `uid` of your user on host.

**Comment by TLyngeJ** [comment]
@achekulaev You're right. That was a lucky punch. This only works because the user on the host is the first I created and the same goes with the container. Therefore they share the same uid and gid. Guess I just hit the famous "90%" use case there :-)

According to https://docs.docker.com/compose/yml/ the `environment` key will grab the corresponding host variable if you don't pass a value. Maybe you can use that instead?

> Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values.

**Comment by lmakarov** [comment]
I've just committed https://github.com/blinkreaction/drude/commit/360f181047483fd714586f1378e6c1f31b9bef05, which  lets the user id in the cli container to be set to your host use id.

@TLyngeJ would you be willing to test this?

Steps:
- Switch cli to `image: blinkreaction/drupal-cli:latest`
- Update dsh to the dev version: `DRUDE_BRANCH=develop dsh self-update`
- `export DRUDE_SET_UID=$(id -u)` to let `dsh` know your uid
- `dsh up`

**Comment by TLyngeJ** [comment]
Hi @lmakarov 

I have not forgot about this. Just been quite busy lately. But I'm getting there... Eventually :-)

**Comment by lmakarov** [comment]
@TLyngeJ We've got some happy Linux users so far using https://github.com/blinkreaction/drude/issues/56#issuecomment-153492700.
It does not take long to switch and try it ;)

**Comment by TLyngeJ** [comment]
Hi @lmakarov 

Was about to test patch you made. Review looks good so far. But I'm not having issues running `dsh mysql-import`.

I'm running dsh 1.9.3 and the latest CLI container. I did not run `dsh install prerequisites`, as it said that it might break my current installation of docker, which doesn't sound promising.

The command results in

```
docroot :: (master*) » dsh mysql-import ../db.sql
[!] This will drop the existing database. Continue? [y/n]: y
Do you really want to drop all tables in the database drupal? (y/n): y
Importing db.sql into the database...
bash: $'\E[?25h\E[0G\E[K\E[?25h\E[0G\E[Kmysql': command not found
   0 B 0:00:00 [   0 B/s] [>                                                    ]  0%            
dsh: mysql-import failed
```

`dsh sqlc` results in a similar error message. `dsh drush sqlc` seems to work flawlessly though.

Is this a new issue/bug or is it a setup issue in my end?

**Comment by TLyngeJ** [comment]
Some debug info:
I amended the dsh script

```
    # Use pv for interactive shells only.
    if is_tty ; then
        # Check if we have a gzipped dump and treat it differently.
        if [[ $filename == *.gz ]]; then
            file_size=$(gzip -l $1 | sed -n 2p | awk '{print $2}')
            run "zcat ./$pathdiff/$filename | pv --size $file_size | "$sql_connect
        else
      echo "connection string: "$sql_connect
      echo "Doesn't work"
            run "pv ./$pathdiff/$filename | "$sql_connect
      echo "Works"
            run "pv ./$pathdiff/$filename | mysql --user=drupal --password=123 --database=drupal --host=172.17.0.4"
        fi
```

And this is the result:

```
docroot :: (master*) » dsh sqli -y ../db.sql
Do you really want to drop all tables in the database drupal? (y/n): y
Importing db.sql into the database...
mysql --user=drupal --password=123 --database=drupal --host=172.17.0.4
Doesn't work
bash: $'\E[?25h\E[0G\E[K\E[?25h\E[0G\E[Kmysql': command not found
   0 B 0:00:00 [   0 B/s] [>                                                 ]  0%            
Works
68.7MiB 0:01:10 [1001KiB/s] [===============================================>] 100%            
dsh: mysql-import finished
```

Not sure what is up with the connection string when it comes from the variable though.

**Comment by achekulaev** [comment]
@TLyngeJ were you changing PS1 recently to make it more colorful?
@lmakarov I guess running clean_string on $file_size should solve the problem above

**Comment by TLyngeJ** [comment]
@achekulaev Yes, both my zsh (which I primarily use) and bash has a colourful PS1. I even think that this version of Ubuntu (15.10) is "born" with a colourful bash. But I'm not completely sure.

**Comment by TLyngeJ** [comment]
Despite the little bump on the road, getting the DB imported (which I solved by doing `dsh bash` and ran the `drush sqlc < db.sql` from there) this fix seems to work. I'm a much happier Drupal developer now :-)

**Comment by 3mkay** [comment]
I've been setting-up a few new users and they've all experienced this problem. 
All users are on OS X and have some colour alterations to their shell.

After upgrading my dsh to 1.9.3 (from 1.9.1) I also get the same error on OSX with oh-my-zsh
