### ISSUE TITLE
Is it possible to setup drush aliases to use with drude containers?

### ISSUE THREAD

**Issue by frederickjh** [blinkreaction/drude#57]
Hi!
Is it possible to create drush aliases to work with drude containers? If so can you include a sample aliases file?

Thanks!
Frederick

**Comment by achekulaev** [comment]
Hi. Yes sure. 
You need to have your database available from host. 
If you're using Drude's vhost proxy then run `dsh st` and look for VM port to which your database container is mapped to. In this example `proj_db_1` is mapped to port `32772` on VM:

```
$ dsh ps
   Name                  Command               State                       Ports
----------------------------------------------------------------------------------------------------
proj_cli_1   /opt/startup.sh /bin/sh -c ...   Up
proj_db_1    /entrypoint.sh mysqld            Up      0.0.0.0:32772->3306/tcp
proj_web_1   /bin/sh -c /opt/startup.sh ...   Up      0.0.0.0:32773->443/tcp, 0.0.0.0:32774->80/tcp
```

In my other case I don't use vhost proxy. I have it disabled in my `vagrant.yml` while in `docker-compose.yml` I have my db container's `3306` port mapped to `3306` on VM:

```
db:
  hostname: db
  image: blinkreaction/mysql:5.5
  ports:
    - "3306:3306"
```

So in this example I'll use second case with port `3306` mapped on VM to DB container's `3306`.
VM's IP by default is `192.168.10.10` unless you customized it. If you customized it then use your IP.

1) You create a multisite subfolder `.../projects/project/docroot/sites/drush`
2) Place `settings.php` in that `sites/drush` folder that should contain real database credentials (default database in Drude is created with user 'drupal' password '123':

```
<?php 

$base_url = 'http://yoursite.drude';    // TODO: change to your URL
$databases = array (                // Don't need to change to your connection details
  'default' =>
    array (
      'default' =>
        array (
          'database' => 'drupal',
          'username' => 'drupal',
          'password' => '123',
          'host' => '192.168.10.10',    //TODO: use your IP if you customized it
          'port' => '3306',    //TODO: change your port number if you use vhost proxy
          'driver' => 'mysql',
          'prefix' => '',
        ),
    ),
);
```

3) Then you create drush alias. In my case I have a file `~/.drush/proj.aliases.drushrc.php`
With following lines

```
<?php

$aliases['proj.parent'] = array(
    'root' => '/path/to/your/project/docroot',  
);

$aliases['proj'] = array(
  'parent' => '@proj.parent',
  'uri'  => 'drush',
);
```

If you did everything right you should be able to execute `drush @proj st`

**Comment by lmakarov** [comment]
Hi @frederickjh, can you elaborate on your use case?

You do not normally need a drush alias to use drush with a site running on Drude.
Simply use Drush inside the CLI container: `dsh drush`

If you are not using `default/settings.php` for the site, then you have several options:
- cd into sites/<sitename> and run `dsh drush status` from here
- use `dsh drush -l <site_domain> status`
- create a drush alias file defining the `uri` there (see instruction below on where to put the file and how to name it)
  
  ```
  $aliases['<drude>'] = array(
    'root' => '/var/www/docroot',
    'uri'  => 'hello-world.drude',
  );
  ```
  
  ```
  dsh drush @<project>.<drude> status
  ```

If you have remote project aliases, put them into `/drush/aliases/<project>.aliases.drushrc.php` in the project repo and Drush will automatically pick them up. Check with `dsh drush sa`
You SSH key will also be picked up by the CLI container, so you should be able to connect to remote site instances without issues.

**Comment by frederickjh** [comment]
Hi @lmakarov!

<pre>drush sql-sync @website.prod @website.localdev</pre>

Syncing the production database to the local development environment via drush is the use case.

The database connection was what was tripping me up. I am on Linux not running a vhost. Port 3306 is in use on the host machine. I basically meant that I needed to set the port number in the settings.php file to the same port that I use to access it on the host machine.

I could not get the variables for the database settings in the settings.php file to work with drush.

<pre>$databases = array (
  'default' => 
  array (
    'default' => 
    array (
      'database' => getenv('DB_1_ENV_MYSQL_DATABASE'),
      'username' => getenv('DB_1_ENV_MYSQL_USER'),
      'password' => getenv('DB_1_ENV_MYSQL_PASSWORD'),
      'host' => getenv('DB_1_PORT_3306_TCP_ADDR'),
      'port' => '',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);</pre>

 I had to  replace these with the settings the variables would have represented, but maybe this has something to do with the fact that I am not running in a vhost.

I have in the mean time put together my own container that meets my needs. I do like and use the dsh command from the project.

God Bless!
Frederick

**Comment by lmakarov** [comment]
@frederickjh here's an example from one of my project init scripts (`dsh init`):

`dsh drush -l example.com sql-sync @project.prod @self -y`

This will sync the DB from `@project.prod` to the site you have running in Drude.
I personally do not even have drush installed on my Mac anymore. Using containers/Drude for this :)

**Comment by frederickjh** [comment]
Hi @lmakarov! Where are you running that example from? From a docker container? Which one? Boot2Docker virtual machine?  

I am still unable to get the sql-sync working. Drush instructions state that one site must be local. Both cannot be remote. Having the database server on a different container than  drush is on makes this difficult to make it work or maybe impossible.

I have been able to do a drush rsync of my files from the cli container. 

But I think that I have decided that to run the sql-sync from the host or the cli container will not work or I have not found a way to convince drush that the website is local.  I have one container that both mysql and apache2 are in. I think that my next step will be to be to get my alias file into that container then try the drush rsync and sql-sync commands from there.  Unless of course you have a better idea that you think might work better.

Thanks again for your help!

Frederick

**Comment by lmakarov** [comment]
@frederickjh I run that from my Mac host in the `<path-to-project>/docroot` directory. Should also work the same way in B2D.

If you are in the CLI console (`dsh bash`), then `cd /var/www/docroot` and `drush -l example.com sql-sync @project.prod @self -y`

In all of these cases there is one local site (`...-l example.com ... @self...`) and one remote site (`... @project.prod ...`).  
Behind the scenes `dsh drush` opens a console to cli and runs drush there.

**Comment by alanburke** [comment]
@lmakarov Perhaps an odd question, but where are the Drush alises for the remote sites defined.
running 'dsh drush sa'  doesn't list the aliases defined in my ~/.drush folder?

**Comment by frederickjh** [comment]
I believe that the drude project is copying these in from the .drush folder. See the startup.sh script for more info. I believe that it should copy in the drush and ssh settings from the host into the container on startup, so if you make changes that you want to see you need to stop the container then start it so it will copy the changes.

**Comment by lmakarov** [comment]
@alanburke, @frederickjh is right - the CLI container will have access to, copy and use the ~/.ssh and  ~/.drush folders from your host.
In addition you should be able to place drush aliases in the project repo (preferable IMO) under:
- /drush/aliases
- /docroot/sites/all/drush

See our [D7 sample project](https://github.com/blinkreaction/drude-d7-testing) - it is using [/drush/aliases/drude.aliases.drushrc.php](https://github.com/blinkreaction/drude-d7-testing/blob/master/drush/aliases/drude.aliases.drushrc.php)

**Comment by lmakarov** [comment]
I just did some testing to confirm the alias visibility with drush7 vs drush8.

drush7

```
~/.drush
project/docroot/drush
project/docroot/sites/all/drush
```

drush8

```
~/.drush/*
project/drush/*
project/docroot/drush/*
project/docroot/sites/all/drush/*
project/docroot/sites/sitename/drush/*
```

As you can see drush8 will scan directories down for alias files. It also scans two additional location compared to drush7:

```
project/drush/*
project/docroot/sites/sitename/drush/*
```

So the most **failsafe project specific locations for site aliases are**:

```
project/docroot/drush
project/docroot/sites/all/drush
```

We have an extra configuration in the CLI container that includes `repo/docroot/drush/aliases` folder as well. It assumes that the there is a git repo in the project root and won't work without the repo.
I'm going to abandon that assumption and approach all together.

I'm considering this closed. **Please stick with one of the failsafe options outlined above.**
