### ISSUE TITLE
Databases do not persist

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#6]
On Friday, with the assistance of @lmakarov I created two docker containers with 1 Drupal site each.  These were hosted at http://192.168.10.10/ and http://192.168.10.11/.

I returned on Monday, ran the following two commands: `vagrant up` and `fig up -d`.  I attempted to load both sites, but one was unavailable with the following message:

![broken db](https://cloud.githubusercontent.com/assets/1197335/6447985/aad737e2-c0e4-11e4-8129-a02251361500.png)

The other site continued to function throughout the day.  This morning I booted up vagrant and docker again and found that _both_ sites were returning this message.  I sshed to one of the sites, and found that there was a database called "drupal" but that database contained now tables:
## MySQL session:

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| drupal             |
+--------------------+
2 rows in set (0.00 sec)

mysql> use drupal;
Database changed

mysql> show tables;
Empty set (0.00 sec)
```

I am reasonably sure that these databases were stored using "volume containers" (which should make them persistent, right?).  Here are the `fig.yml` files I used to generate both sites https://gist.github.com/MKorostoff/1989d781a1f855423072

**Comment by lmakarov** [comment]
@MKorostoff did you do anything else with the fig.yml files or Vagrantfile?

There are two possible causes I see:
- the vagrant box was reinitialized (`vagrant destroy`, then `vagrant up`)
- the containers got reinitialized by fig (`fig stop`, then `fig rm`, then `fig up -d`)

**Comment by mkorostoff** [comment]
I'm 95% sure I never gave the command `vagrant destroy`, and 100% sure I never gave the commands `fig stop` or `fig rm`.  I may have given the command `vagrant halt` though I don't recall specifically.  I've definitely given the commands `vagrant up` and `fig up -d` several times each.

Here's my Vagrantfile, though I think it's just the stock one https://gist.github.com/MKorostoff/ed15cf74507818b49d55

**Comment by mkorostoff** [comment]
Just an update—my databases have persisted for the past three days.  So, that's good news!
