### ISSUE TITLE
Can't connect to MySQL server

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#7]
After running `fig up -d`, I attempted to load my Drupal site in a web browser.  I receive the following error message:

![mysql](https://cloud.githubusercontent.com/assets/1197335/6470325/fbcbcbfa-c1b0-11e4-905f-2c544012ffa2.png)

I SSHed to the container and attempted to run the command `drush sqlc` but received the following error:

```
ERROR 2003 (HY000): Can't connect to MySQL server on '172.17.0.17' (113)
```

This may be related to #6, but I'm pretty sure it is an unrelated issue.

**Comment by lmakarov** [comment]
What does your `fig ps` and `docker ps -a` output look like?

**Comment by mkorostoff** [comment]
fig ps:

```
$ fig ps
fig.yml is deprecated and will not be supported in future. Please rename your config file to docker-compose.yml

    Name                   Command               State             Ports           
----------------------------------------------------------------------------------
demo_db_1       /entrypoint.sh mysqld            Exit 1                            
demo_dbdata_1   /entrypoint.sh echo Data-o ...   Exit 0                            
demo_web_1      /usr/bin/supervisord -n          Up       192.168.10.11:80->80/tcp 
```

docker ps:

```
 $ docker ps -a
CONTAINER ID        IMAGE                                   COMMAND                CREATED             STATUS                         PORTS                          NAMES
4958ac11056f        blinkreaction/drupal-nginx-php:latest   "/usr/bin/supervisor   About an hour ago   Up About an hour               192.168.10.11:80->80/tcp       demo_web_1           
a526cf1be08a        mysql:5.5                               "/entrypoint.sh mysq   About an hour ago   Exited (1) About an hour ago                                  demo_db_1            
9a0e53de6c3b        mysql:5.5                               "/entrypoint.sh echo   About an hour ago   Exited (0) About an hour ago                                  demo_dbdata_1        
3a819ed3c060        blinkreaction/drupal-nginx-php:latest   "/usr/bin/supervisor   About an hour ago   Up About an hour               192.168.10.10:80->80/tcp       drupal7_web_1        
40f7f452f1e7        mysql:5.5                               "/entrypoint.sh mysq   About an hour ago   Up About an hour               192.168.10.10:3306->3306/tcp   drupal7_db_1         
b5facfb7867e        mysql:5.5                               "/entrypoint.sh echo   About an hour ago   Exited (0) About an hour ago                                  drupal7_dbdata_1     
ae6729af2f72        blinkreaction/drupal-nginx-php:latest   "bash"                 25 hours ago        Exited (0) 5 hours ago         80/tcp                         drupal7_web_run_2    
e7716906ec5e        mysql:5.5                               "/bin/echo"            26 hours ago        Exited (0) 26 hours ago                                       suspicious_bardeen   
41d21429d40c        blinkreaction/drupal-nginx-php:latest   "bash"                 27 hours ago        Exited (0) 26 hours ago        80/tcp                         demo_web_run_1       
d9cf99b6bb4a        blinkreaction/drupal-nginx-php:latest   "bash"                 27 hours ago        Exited (0) 26 hours ago        80/tcp                         drupal7_web_run_1    
7a558678b8e8        mysql:5.5                               "/bin/echo"            28 hours ago        Exited (0) 28 hours ago                                       determined_wozniak  
```

**Comment by lmakarov** [comment]
The db container is not running. Do `fig up -d` and check with `fig ps` that it's up.
Looks like there was an error running it (Exit 1). Check the log output with `fig logs db` and post here.

**Comment by mkorostoff** [comment]
```
 $ fig logs db
fig.yml is deprecated and will not be supported in future. Please rename your config file to docker-compose.yml

Attaching to demo_db_1
db_1 | 150303 19:07:02 [Note] Plugin 'FEDERATED' is disabled.
db_1 | 150303 19:07:02 InnoDB: The InnoDB memory heap is disabled
db_1 | 150303 19:07:02 InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1 | 150303 19:07:02 InnoDB: Compressed tables use zlib 1.2.3
db_1 | 150303 19:07:02 InnoDB: Using Linux native AIO
db_1 | 150303 19:07:02 InnoDB: Initializing buffer pool, size = 128.0M
db_1 | 150303 19:07:02 InnoDB: Completed initialization of buffer pool
db_1 | InnoDB: Error: log file ./ib_logfile0 is of different size 0 33554432 bytes
db_1 | InnoDB: than specified in the .cnf file 0 5242880 bytes!
db_1 | 150303 19:07:02 [ERROR] Plugin 'InnoDB' init function returned error.
db_1 | 150303 19:07:02 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1 | 150303 19:07:02 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1 | 150303 19:07:02 [ERROR] Aborting
db_1 | 
db_1 | 150303 19:07:02 [Note] mysqld: Shutdown complete
db_1 | 
```

**Comment by lmakarov** [comment]
I've seen this issue before

```
db_1 | InnoDB: Error: log file ./ib_logfile0 is of different size 0 33554432 bytes
db_1 | InnoDB: than specified in the .cnf file 0 5242880 bytes!
```

Not sure what causes it and I cannot offer a better solution that killing the dbdata container for now: `fig stop && fig rm dbdata && fig up -d`

**Comment by mkorostoff** [comment]
`fig stop && fig rm dbdata && fig up -d` didn't change anything, _but_ `fig stop && fig rm db && fig up -d` did the trick (note the second command here is `fig rm db` rather than `fig rm dbdata`).  Once I ran that, I was able to SSH to the container and run `drush si` successfully.

Even though I don't really understand this ecosystem, this solution actually makes intuitive sense to me, because `demo_db_1`was the container showing "Exit 1", while "demo_dbdata_1" was showing "Exit 0."  (I guess Exit 0 means its a volume container?)

## Before `fig rm db`

![figps](https://cloud.githubusercontent.com/assets/1197335/6490925/b7dd63be-c277-11e4-98ad-2b674565de10.png)

## After `fig rm db`

![figps2](https://cloud.githubusercontent.com/assets/1197335/6490932/d1b02560-c277-11e4-8c3d-2840e761436c.png)

Just to clarify, does `fig rm dbdata` destroy data?  Not that it matters, just curious.

**Comment by lmakarov** [comment]
It turns out both db and dbdata share the same volume (/var/lib/mysql). The volume is mounted in both containers and is physically the same folded on the Docker Host VM. Docker does not devele a volume while there is at least one container using it. So removing dbdata or db, but not both does not remove the shared /var/lib/mysql volume. Both need to be removed. The easiest thing to do is `fig stop && fig rm -f && fig up -d`.

I've also learned that the official mysql images defines the /var/lib/mysql volume itself.
This means that dbdata container is pointless and can be excluded completely. I will update the docker-compose.yml file and remove it.

**Comment by softeg** [comment]
I have the same issue, idon't khow why ?
docker-compose ps   

##   Name                Command               State                     Ports                   

cn_cli_1   /bin/sh -c /opt/startup.sh       Up  
cn_db_1    /entrypoint.sh mysqld            Exit 1  
cn_web_1   /bin/sh -c /opt/startup.sh ...   Up       0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
docker-compose logs db  
Attaching to cn_db_1
db_1 | 150327 23:26:44 [Note] Plugin 'FEDERATED' is disabled.
db_1 | 150327 23:26:44 InnoDB: The InnoDB memory heap is disabled
db_1 | 150327 23:26:44 InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1 | 150327 23:26:44 InnoDB: Compressed tables use zlib 1.2.3
db_1 | 150327 23:26:44 InnoDB: Using Linux native AIO
db_1 | 150327 23:26:44 InnoDB: Initializing buffer pool, size = 256.0M
db_1 | 150327 23:26:44 InnoDB: Completed initialization of buffer pool
db_1 | InnoDB: Error: log file ./ib_logfile0 is of different size 0 5242880 bytes
db_1 | InnoDB: than specified in the .cnf file 0 33554432 bytes!
db_1 | 150327 23:26:44 [ERROR] Plugin 'InnoDB' init function returned error.
db_1 | 150327 23:26:44 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1 | 150327 23:26:44 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1 | 150327 23:26:44 [ERROR] Aborting
db_1 | 
db_1 | 150327 23:26:44 [Note] mysqld: Shutdown complete
db_1 |

**Comment by softeg** [comment]
to correct this issue you need to run this command : 

docker-compose stop && docker-compose rm db && docker-compose up -d
