### ISSUE TITLE
Problems on Windows: sh: docker_compose: not found

### ISSUE THREAD

**Issue by alexander-danilenko** [blinkreaction/drude#73]
Steps for bug replicate: 

```
dsh up 
```

all works good, containers started successfully.

```
dsh bash
```

returns error: 

```
sh: docker_compose: not found
Error response from daemon: no such id: bash
Connection to 127.0.0.1 closed.
```

Workaround is: 

```
vagrant ssh -c 'docker exec -it <container_id> bash'
```

**Comment by lmakarov** [comment]
@fat763 I have a fix available now. Can you please test it before I push a release?

In Babun run the following:

```
B2D_BRANCH=develop dsh install prerequisites
DRUDE_BRANCH=feature/winpty dsh self-update
```

Then try `dsh bash` again

**Comment by alexander-danilenko** [comment]
Thank you, @lmakarov!

**Comment by lmakarov** [comment]
This should now be fixed in the develop branch (`DRUDE_BRANCH=develop dsh self-update`)
