### ISSUE TITLE
"Drush 7.0.0 does not support Drupal 8" on D8 fresh install

### ISSUE THREAD

**Issue by comxd** [blinkreaction/drude#75]
Hi,

It's bug a simply a needed upgrade for Drush?

**Comment by lmakarov** [comment]
@comxd The cli container has all 3 drush versions:
- `drush6`
- `drush7` (`drush`) - this is the current default version, also called by `dsh drush`
- `drush8`

So for D8 you should use `drush8` (if inside cli) or `dsh exec drush8` (outside of the cli container).

**Comment by comxd** [comment]
Oh yes thanks!
