### ISSUE TITLE
Project root and init script detection improvements

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#76]
1. `yml_get_path()`
   - fix: should only look for `docker-compose.yml`
   - improvement: stores most recently used project root path in a env variable, compares it with the current project root and outputs a message when the project root path is changing
2. `init()`
   - should be using upfind() directly to find the `.drude` folder and init script in it
   - should output a message with the path to the init script it found and intends to run

**Comment by achekulaev** [comment]
Done in dev
