### ISSUE TITLE
How do I change the php version?

### ISSUE THREAD

**Issue by TLyngeJ** [blinkreaction/drude#78]
Admitted, I've not been upgrading Drude for quite a while. And now that I did, I got a bunch of projects that needs PHP 5.3, 5.4 or 5.5.

After PHP has been removed from the web container, to run entirely on the CLI container, I can't figure out how to change the PHP version. It's probably in the documentation, but I can't see it anywhere.

What am I missing?

**Comment by lmakarov** [comment]
@TLyngeJ we are no longer using older PHP versions on our projects as they are EOL at this point or getting there pretty soon (http://php.net/supported-versions.php). Thus Drude only supports PHP 5.6 at the moment.

Support for switching arbitrary versions would be great (e.g. via https://github.com/php-build/php-build), however it is a pretty tedious thing to maintain.
Early attempts of that are here: https://github.com/blinkreaction/docker-drupal-cli/tree/feature/php-build

**Comment by TLyngeJ** [comment]
Roger that! Thanks for the info.
