### ISSUE TITLE
Сontainer name vs service name distinction in dsh

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#83]
Review and update the terminology around `container` vs `service` in `dsh` | `dsh help`.
Most of dsh commands involve a service name as an argument and not a container name - this has to be clearly communicated.

Aslo, `dsh ps` (which triggers `docker-compose ps`) lists container names instead of service names, which is confusion for newcomers. This need to be reported [upstream](https://github.com/docker/compose) as a improvement suggestion.

**Comment by achekulaev** [comment]
Documentation is updated in development branch. 
Request sent to upstream team here: https://github.com/docker/compose/issues/2369
