### ISSUE TITLE
dsh commands produce shifted output

### ISSUE THREAD

**Issue by achekulaev** [blinkreaction/drude#87]
Recently dsh commands started to produce shifted output

![1 dsh 2fusers 2fshaft 2fsites 2fdrude_projects 2fvoya_im 28bash 29 2016-03-04 20-48-29](https://cloud.githubusercontent.com/assets/402007/13536913/6557d160-e210-11e5-9bb6-ed402b8d5cac.png)

Removing `tr` command that trims `\r` from docker-compose output seems to solve the problem (see `docker_compose` function). But it is (probably?) needed for windows. 

Check if it's needed for windows and make a change.

**Comment by achekulaev** [comment]
cc @lmakarov hotfix candidate

**Comment by achekulaev** [comment]
@lmakarov could you check if we're still good on windows?

**Comment by david-hernandez** [comment]
I don't have access to Windows anywhere. :( Can anyone else test?

**Comment by lmakarov** [comment]
Did some testing on Mac and Windows. https://github.com/blinkreaction/drude/commit/f6d69074b5f16a42285ddc03a1d3f7a7d294d0fa does fix the issue on Mac, however on Windows the issue is still present.

**Comment by david-hernandez** [comment]
I guess that makes sense. The trim is what causes the shifting, but the comment there says the trim is needed on Windows only to fix some other problem. This would just stop the shifting on non-Windows, where the trim isn't necessary.
