### ISSUE TITLE
Update reminder

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/drude#98]
We need a nagging update reminder and clear update process instructions.

Many users will experience issues, which were addressed a long time ago.
In most cases they are using older version of prerequisites (boot2docker-vagrant, docker cli, docker-compose cli, virtualbox, vagrant), dsh and/or containers, but have no idea how or when to update.

**Comment by achekulaev** [comment]
dsh update reminder done in develop. Not sure we'll need other reminders.
